/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.corretora_cunha.view;

import javax.swing.JOptionPane;
import br.com.corretora_cunha.dto.AdministradorDTO;
import br.com.corretora_cunha.ctr.AdministradorCTR;
/**
 *
 * @author raissa_sc6
 */
public class LoginVIEW2 extends javax.swing.JFrame {

      AdministradorCTR administradorCTR = new AdministradorCTR(); //Cria um obejto clienteCTR
    AdministradorDTO administradorDTO = new AdministradorDTO();
    
  
    public LoginVIEW2() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblcod_loja4 = new javax.swing.JLabel();
        lblloja2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblemail = new javax.swing.JLabel();
        log_usu = new javax.swing.JTextField();
        lblsenha = new javax.swing.JLabel();
        sen_usu = new javax.swing.JPasswordField();
        btnLogar = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JLabel();
        lbltitle = new javax.swing.JLabel();

        lblcod_loja4.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lblcod_loja4.setText("Senha::");

        lblloja2.setFont(new java.awt.Font("Vivaldi", 3, 36)); // NOI18N
        lblloja2.setForeground(new java.awt.Color(242, 175, 88));
        lblloja2.setText("Login");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));

        lblemail.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lblemail.setText("E-mail:");

        log_usu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                log_usuKeyPressed(evt);
            }
        });

        lblsenha.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lblsenha.setText("Senha:");

        sen_usu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sen_usuKeyPressed(evt);
            }
        });

        btnLogar.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        btnLogar.setText("Logar");
        btnLogar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogarMouseClicked(evt);
            }
        });

        btnCancelar.setText("Sair");
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });

        lbltitle.setFont(new java.awt.Font("Vivaldi", 3, 36)); // NOI18N
        lbltitle.setForeground(new java.awt.Color(54, 74, 58));
        lbltitle.setText("Login");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addGap(106, 106, 106)
                .addComponent(btnLogar)
                .addGap(145, 145, 145))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblsenha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sen_usu, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblemail)
                                .addGap(18, 18, 18)
                                .addComponent(log_usu, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(lbltitle)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lbltitle)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblemail)
                    .addComponent(log_usu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sen_usu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblsenha))
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogar)
                    .addComponent(btnCancelar))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void log_usuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_log_usuKeyPressed

        // TODO add your handling code here:
    }//GEN-LAST:event_log_usuKeyPressed

    private void sen_usuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sen_usuKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_sen_usuKeyPressed

    private void btnLogarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogarMouseClicked
        if(verificaPreenchimento()){
            logar();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogarMouseClicked

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void logar(){
        administradorDTO.setEmail_adm(log_usu.getText());
        administradorDTO.setSenha_adm(String.valueOf(sen_usu.getPassword()));
        if(administradorCTR.logarAdm(administradorDTO)){
            this.dispose();
            new PrincipalVIEW().setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(null, "Login ou senha\nIncorreto!!!");
        }
    }//Fecha método gravar()
    
    
    /**
     * Método utilizado para verificar se os campos estão preenchidos.
     * @param não recebe parametro.
     * @return boolean false(campo não preenchido) true(campo preenchido).
     */
    private boolean verificaPreenchimento() {                            
        if(log_usu.getText().equalsIgnoreCase("")){
              JOptionPane.showMessageDialog(null, "O campo Login deve ser preenchido");
              log_usu.requestFocus();
              return false;
        }
        else{
            if((sen_usu.getPassword().equals(""))){
                JOptionPane.showMessageDialog(null, "O campo Senha deve ser preenchido");
                sen_usu.requestFocus();
                return false;
            }
            else{
                return true;
            }//Fecha else sen_usu
        }//Fecha else log_usu
    }//Fecha método verificaPreenchimento()

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCancelar;
    private javax.swing.JLabel btnLogar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblcod_loja4;
    private javax.swing.JLabel lblemail;
    private javax.swing.JLabel lblloja2;
    private javax.swing.JLabel lblsenha;
    private javax.swing.JLabel lbltitle;
    private javax.swing.JTextField log_usu;
    private javax.swing.JPasswordField sen_usu;
    // End of variables declaration//GEN-END:variables
}
