/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.corretora_cunha.view;

/**
 *
 * @author ra6sa
 */

import javax.swing.*;
import br.com.corretora_cunha.view.clientes.ClienteVIEW;
import br.com.corretora_cunha.view.clientes.ClientesCadastrar;
import br.com.corretora_cunha.view.corretores.CorretorVIEW;
import br.com.corretora_cunha.view.negocio.NegocioVIEW;
import br.com.corretora_cunha.view.propriedades.PropriedadeRurais;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
        
public class PrincipalVIEW extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalVIEW
     */
    public PrincipalVIEW() {
        initComponents();
        this.setLocationRelativeTo(null);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFundo = new javax.swing.JPanel();
        lblPropriedadeRural = new javax.swing.JLabel();
        lblClientes = new javax.swing.JLabel();
        lblCorretores = new javax.swing.JLabel();
        lblNegocio = new javax.swing.JLabel();
        btnEmail = new javax.swing.JLabel();
        btnSair = new javax.swing.JLabel();
        imgPropRural = new javax.swing.JLabel();
        imgCli = new javax.swing.JLabel();
        imgCor = new javax.swing.JLabel();
        imgNeg = new javax.swing.JLabel();
        imgEmail = new javax.swing.JLabel();
        imgNomeSistema = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setFocusTraversalPolicyProvider(true);
        setUndecorated(true);

        jPanelFundo.setBackground(new java.awt.Color(255, 255, 255));
        jPanelFundo.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(8, 89, 43)));

        lblPropriedadeRural.setText("Propriedades Rurais");
        lblPropriedadeRural.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPropriedadeRuralMouseClicked(evt);
            }
        });

        lblClientes.setText("Clientes");
        lblClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblClientesMouseClicked(evt);
            }
        });

        lblCorretores.setText("Corretores");
        lblCorretores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCorretoresMouseClicked(evt);
            }
        });

        lblNegocio.setText("Negociações");
        lblNegocio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNegocioMouseClicked(evt);
            }
        });

        btnEmail.setText("Acessar E-mail");
        btnEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEmailMouseClicked(evt);
            }
        });

        btnSair.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/corretora_cunha/imgs/door.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSairMouseClicked(evt);
            }
        });

        imgPropRural.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/corretora_cunha/imgs/prural2.png"))); // NOI18N
        imgPropRural.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgPropRuralMouseClicked(evt);
            }
        });

        imgCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/corretora_cunha/imgs/icCli.png"))); // NOI18N
        imgCli.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        imgCli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgCliMouseClicked(evt);
            }
        });

        imgCor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/corretora_cunha/imgs/icCor.png"))); // NOI18N
        imgCor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgCorMouseClicked(evt);
            }
        });

        imgNeg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/corretora_cunha/imgs/icNeg.png"))); // NOI18N
        imgNeg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgNegMouseClicked(evt);
            }
        });

        imgEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/corretora_cunha/imgs/icEmail.png"))); // NOI18N
        imgEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgEmailMouseClicked(evt);
            }
        });

        imgNomeSistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/corretora_cunha/imgs/nome150.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanelFundoLayout = new javax.swing.GroupLayout(jPanelFundo);
        jPanelFundo.setLayout(jPanelFundoLayout);
        jPanelFundoLayout.setHorizontalGroup(
            jPanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFundoLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(lblPropriedadeRural)
                .addGap(185, 185, 185)
                .addComponent(lblClientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNegocio)
                .addGap(95, 95, 95))
            .addGroup(jPanelFundoLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(imgPropRural)
                .addGroup(jPanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelFundoLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(imgNomeSistema)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelFundoLayout.createSequentialGroup()
                        .addGroup(jPanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelFundoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(imgCor)
                                .addGap(93, 93, 93)
                                .addComponent(imgEmail))
                            .addGroup(jPanelFundoLayout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addComponent(imgCli)
                                .addGap(83, 83, 83)
                                .addComponent(imgNeg)))
                        .addContainerGap(96, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFundoLayout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(lblCorretores)
                .addGap(178, 178, 178)
                .addComponent(btnEmail)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelFundoLayout.setVerticalGroup(
            jPanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFundoLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelFundoLayout.createSequentialGroup()
                        .addComponent(imgNomeSistema)
                        .addGap(18, 18, 18)
                        .addComponent(imgCli))
                    .addGroup(jPanelFundoLayout.createSequentialGroup()
                        .addComponent(btnSair)
                        .addGap(90, 90, 90)
                        .addGroup(jPanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imgPropRural, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(imgNeg, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPropriedadeRural)
                    .addComponent(lblClientes)
                    .addComponent(lblNegocio))
                .addGap(39, 39, 39)
                .addGroup(jPanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFundoLayout.createSequentialGroup()
                        .addComponent(imgEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEmail))
                    .addGroup(jPanelFundoLayout.createSequentialGroup()
                        .addComponent(imgCor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCorretores)))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClientesMouseClicked
       abrirClientes();
    }//GEN-LAST:event_lblClientesMouseClicked

    private void lblCorretoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCorretoresMouseClicked
        abrirCor();
    }//GEN-LAST:event_lblCorretoresMouseClicked

    private void lblPropriedadeRuralMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPropriedadeRuralMouseClicked
        abrirPropRu();
    }//GEN-LAST:event_lblPropriedadeRuralMouseClicked

    private void lblNegocioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNegocioMouseClicked
        abrirNeg();
    }//GEN-LAST:event_lblNegocioMouseClicked

    private void btnEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmailMouseClicked
        try {
            abrirEmail();
            // TODO add your handling code here:
        } catch (Exception ex) {
            Logger.getLogger(PrincipalVIEW.class.getName()).log(Level.SEVERE, null, ex);
             JOptionPane.showMessageDialog(null,
                "Não foi possivel abrir o email "+ex);
        }
    }//GEN-LAST:event_btnEmailMouseClicked

    private void btnSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnSairMouseClicked

    private void imgPropRuralMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgPropRuralMouseClicked
       abrirPropRu();
    }//GEN-LAST:event_imgPropRuralMouseClicked

    private void imgCliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgCliMouseClicked
         abrirClientes();
    }//GEN-LAST:event_imgCliMouseClicked

    private void imgCorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgCorMouseClicked
         abrirCor();
    }//GEN-LAST:event_imgCorMouseClicked

    private void imgNegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgNegMouseClicked
        abrirNeg();
    }//GEN-LAST:event_imgNegMouseClicked

    private void imgEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgEmailMouseClicked
         try {
            abrirEmail();
            // TODO add your handling code here:
        } catch (Exception ex) {
            Logger.getLogger(PrincipalVIEW.class.getName()).log(Level.SEVERE, null, ex);
             JOptionPane.showMessageDialog(null,
                "Não foi possivel abrir o email "+ex);
        }
    }//GEN-LAST:event_imgEmailMouseClicked

   
    private void abrirPropRu(){
        try {
            new PropriedadeRurais().setVisible(true);
            this.dispose();
        }catch(Exception e){
              JOptionPane.showMessageDialog(null,
                "Não foi possivel abrir as propriedades rurais "+e);
        }
    }
    
     
    private void abrirClientes(){
       try {
            new ClienteVIEW().setVisible(true);
            this.dispose();
        }catch(Exception e){
              JOptionPane.showMessageDialog(null,
                "Não foi possivel abrir os clientes "+e);
        }
    }
    
    private void abrirCor(){
        try {
            new CorretorVIEW().setVisible(true);
            this.dispose();
        }catch(Exception e){
              JOptionPane.showMessageDialog(null,
                "Não foi possivel abrir os corretores "+e);
        }
    }
    
    private void abrirNeg(){
        try {
            new NegocioVIEW().setVisible(true);
            this.dispose();
        }catch(Exception e){
              JOptionPane.showMessageDialog(null,
                "Não foi possivel abrir os negócios "+e);
        }
    }
    
    private void abrirEmail() throws Exception{
        //rmc dados;
    String url = "https://outlook.live.com/mail/0/";
    try {
        URI uri = new URI(url);
        Desktop desktop = null;
        if (Desktop.isDesktopSupported()) {
            desktop = Desktop.getDesktop();
        }
        if (desktop != null)
            desktop.browse(uri);
        } catch (IOException ioe) {
            ioe.printStackTrace();
            
        } catch (URISyntaxException use) {
            use.printStackTrace();
    }
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnEmail;
    private javax.swing.JLabel btnSair;
    private javax.swing.JLabel imgCli;
    private javax.swing.JLabel imgCor;
    private javax.swing.JLabel imgEmail;
    private javax.swing.JLabel imgNeg;
    private javax.swing.JLabel imgNomeSistema;
    private javax.swing.JLabel imgPropRural;
    private javax.swing.JPanel jPanelFundo;
    private javax.swing.JLabel lblClientes;
    private javax.swing.JLabel lblCorretores;
    private javax.swing.JLabel lblNegocio;
    private javax.swing.JLabel lblPropriedadeRural;
    // End of variables declaration//GEN-END:variables
}
