/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.corretora_cunha.view.negocio;

import br.com.corretora_cunha.ctr.ClienteCTR;
import br.com.corretora_cunha.ctr.NegocioCTR;
import br.com.corretora_cunha.ctr.NegocioCliCTR;
import br.com.corretora_cunha.dto.ClienteDTO;
import br.com.corretora_cunha.dto.NegocioCliDTO;
import br.com.corretora_cunha.dto.NegocioDTO;
import br.com.corretora_cunha.view.PrincipalVIEW;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ra6sa
 */
public class NegocioVIEW extends javax.swing.JFrame {
     private ResultSet rs; // Variavel usada para preenchimeto da tabela e dos campos
     private ResultSet rs2, rs3; // Variavel usada para preenchimeto da tabela e dos campos
     private DefaultTableModel modelo_jtl_consultar_neg; //Variavel para guardar o modelo da tabela
     NegocioDTO negocioDTO = new NegocioDTO(); //Cria um objeto negocioDTO
     NegocioCTR negocioCTR = new NegocioCTR(); //Cria um obejto negocioCTR
     NegocioCliDTO negocioCliDTO = new NegocioCliDTO(); //Cria um objeto clienteDTO
     NegocioCliCTR negocioCliCTR = new NegocioCliCTR(); //Cria um obejto clienteCTR
    ClienteDTO clienteDTO = new ClienteDTO(); //Cria um objeto clienteDTO
     ClienteCTR clienteCTR = new ClienteCTR(); //Cria um obejto clienteCTR
     /**
     * Creates new form NegocioVIEW
     */
    public NegocioVIEW() {
        initComponents();
        this.setLocationRelativeTo(null);
        modelo_jtl_consultar_neg = (DefaultTableModel) tab_consulta.getModel();
       preencheTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNomeSistema = new javax.swing.JLabel();
        lbNegocios = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JLabel();
        lblCadastrar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab_consulta = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(8, 89, 43)));

        lblNomeSistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/corretora_cunha/imgs/nome80.jpg"))); // NOI18N

        lbNegocios.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        lbNegocios.setForeground(new java.awt.Color(8, 89, 43));
        lbNegocios.setText("Negócios");

        btnVoltar.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/corretora_cunha/imgs/left-arrow.png"))); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVoltarMouseClicked(evt);
            }
        });

        lblCadastrar.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        lblCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/corretora_cunha/imgs/plus.png"))); // NOI18N
        lblCadastrar.setText("Cadastrar negócio");
        lblCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCadastrarMouseClicked(evt);
            }
        });

        tab_consulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Data", "Situação", "Clientes"
            }
        ));
        tab_consulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_consultaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tab_consulta);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblNomeSistema)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnVoltar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(148, 148, 148)
                                .addComponent(lbNegocios)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblCadastrar))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 19, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNomeSistema)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVoltar)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(lblCadastrar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(lbNegocios)))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadastrarMouseClicked
        new NegocioCadastrar().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblCadastrarMouseClicked

    private void tab_consultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_consultaMouseClicked
        //Abrir negocio selecionado em NegocioCadastrar
        new NegocioCadastrar(Integer.parseInt(String.valueOf(tab_consulta.getValueAt(tab_consulta.getSelectedRow(), 0)))).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tab_consultaMouseClicked

    private void btnVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarMouseClicked
        new PrincipalVIEW().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVoltarMouseClicked

    /**
     * @param args the command line arguments
     */
 

    private void preencheTabela() {
        try {
            modelo_jtl_consultar_neg.setNumRows(0); //Limpa todas as linhas
            rs = negocioCTR.consultarNegocio(negocioDTO, 5);//Consultar os negocios
            while (rs.next()) { //Enquanto tiver negocios preencha as linhas
                String cli;//cli = nome dos clientes
                //passando os dados para o objeto negocioDTO
                negocioDTO.setId_neg(Integer.parseInt(rs.getString("id_neg")));
                negocioDTO.setData_neg(rs.getString("data_neg"));
                negocioDTO.setSituacao_neg(rs.getString("situacao_neg"));
                
                //passando o id_neg para o objeto negocioCliDTO
                negocioCliDTO.setId_neg(negocioDTO.getId_neg());
                cli = buscaCli(negocioCliDTO);//buscando os nomes dos clientes do negocio
                modelo_jtl_consultar_neg.addRow(new Object[]{ //adicionando linha na tabela
                    negocioDTO.getId_neg(),
                    negocioDTO.getData_neg(),
                    negocioDTO.getSituacao_neg(),
                    cli}
                );
                
            }
        } catch (Exception erTab) {
            System.out.println("Erro SQL: " + erTab);
        }
    }//Fecha método preencheTabela
    
    //Método inicial para buscar o id dos clientes do negocio
    private String buscaCli(NegocioCliDTO negocioCliDTO){
        try {
            //consulta os clientes dos negocios
            rs2 = negocioCliCTR.consultarNegocioCli(negocioCliDTO, 1);
            //StringBuilder para concatenar string em uma variável clientes
            StringBuilder clientes = new StringBuilder();
            while (rs2.next()) {
                clienteDTO.setId_cli(Integer.parseInt(rs2.getString("id_cli")));
                clientes.append(buscaNomeCli(clienteDTO)); //concatenando 
            }
            return clientes.toString();
            } catch (Exception erTab) {
                return "Erro no método buscaCli pelo id: "+ negocioCliDTO.getId_neg();
        }
    }
    //Método inicial para buscar o nome dos clientes do negocio pelo id
    private String buscaNomeCli(ClienteDTO clienteDTO){
        try {
            String nome="";
            rs3 = clienteCTR.consultarCliente(clienteDTO, 1);
            while (rs3.next()) {
                nome = rs3.getString("nome_cli") + "  "; 
            }
            return  nome;
            } catch (Exception erTab) {
                return "Erro no método buscaNomeCli pelo id: "+ clienteDTO.getId_cli();
        }
    }
     
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnVoltar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbNegocios;
    private javax.swing.JLabel lblCadastrar;
    private javax.swing.JLabel lblNomeSistema;
    private javax.swing.JTable tab_consulta;
    // End of variables declaration//GEN-END:variables
}
