/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.corretora_cunha.view.negocio;

import br.com.corretora_cunha.ctr.NegocioCTR;
import br.com.corretora_cunha.dto.NegocioDTO;
import br.com.corretora_cunha.ctr.ClienteCTR;
import br.com.corretora_cunha.ctr.CorretorCTR;
import br.com.corretora_cunha.ctr.NegocioCliCTR;
import br.com.corretora_cunha.ctr.NegocioCorCTR;
import br.com.corretora_cunha.ctr.NegocioPropCTR;
import br.com.corretora_cunha.ctr.PropriedadeCTR;
import br.com.corretora_cunha.dto.ClienteDTO;
import br.com.corretora_cunha.dto.CorretorDTO;
import br.com.corretora_cunha.dto.NegocioCliDTO;
import br.com.corretora_cunha.dto.NegocioCorDTO;
import br.com.corretora_cunha.dto.NegocioPropDTO;
import br.com.corretora_cunha.dto.PropriedadeDTO;
import br.com.corretora_cunha.view.clientes.ClienteVIEW;
import br.com.corretora_cunha.view.corretores.CorretorVIEW;
import br.com.corretora_cunha.view.propriedades.PropriedadeRurais;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ra6sa
 */
public class NegocioCadastrar extends javax.swing.JFrame {
    private int gravar_alterar; //Variavel usada para saber se esta alterando o incluindo
    private ResultSet rs; // Variavel usada para preenchimeto da tabela e dos campos
    private DefaultTableModel modelo_jtl_consultar_cli; //Variavel para guardar o modelo da tabela
    private DefaultTableModel modelo_jtl_consultar_cor; //Variavel para guardar o modelo da tabela
    private DefaultTableModel modelo_jtl_consultar_prop; //Variavel para guardar o modelo da tabela
    NegocioCTR negocioCTR = new NegocioCTR(); //Cria um obejto 
    NegocioDTO negocioDTO = new NegocioDTO(); //Cria um objeto 
    ClienteDTO clienteDTO = new ClienteDTO(); //Cria um objeto clienteDTO
    ClienteCTR clienteCTR = new ClienteCTR(); //Cria um obejto clienteCTR
    CorretorDTO corretorDTO = new CorretorDTO(); //Cria um objeto clienteDTO
    CorretorCTR corretorCTR = new CorretorCTR(); //Cria um obejto clienteCTR
    PropriedadeDTO propriedadeDTO = new PropriedadeDTO(); //Cria um objeto clienteDTO
    PropriedadeCTR propriedadeCTR = new PropriedadeCTR(); //Cria um obejto clienteCTR
    NegocioCliDTO negocioCliDTO = new NegocioCliDTO(); //Cria um objeto NegocioclienteDTO
    NegocioCliCTR negocioCliCTR = new NegocioCliCTR(); //Cria um obejto clienteCTR
    NegocioCorDTO negocioCorDTO = new NegocioCorDTO(); //Cria um objeto NegocioclienteDTO
    NegocioCorCTR negocioCorCTR = new NegocioCorCTR(); //Cria um obejto clienteCTR
    NegocioPropDTO negocioPropDTO = new NegocioPropDTO(); //Cria um objeto NegocioclienteDTO
    NegocioPropCTR negocioPropCTR = new NegocioPropCTR(); //Cria um obejto clienteCTR
    
    /**
     * Creates new form NegocioCadastrar
     */
    public NegocioCadastrar() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.id_neg.disable();
        modelo_jtl_consultar_cli = (DefaultTableModel) tab_consultaCli.getModel();
        modelo_jtl_consultar_cor = (DefaultTableModel) tab_consultaCor.getModel();
        modelo_jtl_consultar_prop = (DefaultTableModel) tab_consultaProp.getModel();
        this.gravar_alterar=1;
        liberaBotoes(false, false, false);
    }
    
    public NegocioCadastrar(int id_neg) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.id_neg.disable();
        modelo_jtl_consultar_cli = (DefaultTableModel) tab_consultaCli.getModel();
        modelo_jtl_consultar_cor = (DefaultTableModel) tab_consultaCor.getModel();
        modelo_jtl_consultar_prop = (DefaultTableModel) tab_consultaProp.getModel();
        this.gravar_alterar=2;
        liberaBotoes(true, true, true);
        preencherCampos(id_neg);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNomeSistema = new javax.swing.JLabel();
        lblNegocio = new javax.swing.JLabel();
        btVoltar = new javax.swing.JLabel();
        id_neg = new javax.swing.JTextField();
        btnExcluir = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        data_neg = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        lblCidade = new javax.swing.JLabel();
        modo_neg = new javax.swing.JTextField();
        lblTelefone = new javax.swing.JLabel();
        situacao_neg = new javax.swing.JTextField();
        botaosalvar = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tab_consultaCli = new javax.swing.JTable();
        btnAddCliente = new javax.swing.JLabel();
        btnRetirarCli = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tab_consultaCor = new javax.swing.JTable();
        btnAddCorretor = new javax.swing.JLabel();
        btnRetirarCor = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab_consultaProp = new javax.swing.JTable();
        btnAddPropRural = new javax.swing.JLabel();
        btnRetirarProp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(8, 89, 43)));

        lblNomeSistema.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        lblNomeSistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/corretora_cunha/imgs/nome80.jpg"))); // NOI18N

        lblNegocio.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        lblNegocio.setForeground(new java.awt.Color(8, 89, 43));
        lblNegocio.setText("Negócio");

        btVoltar.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        btVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/corretora_cunha/imgs/left-arrow.png"))); // NOI18N
        btVoltar.setText("Voltar");
        btVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btVoltarMouseClicked(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/corretora_cunha/imgs/delete.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExcluirMouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados base", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Monotype Corsiva", 0, 18), new java.awt.Color(8, 89, 43))); // NOI18N

        lblNome.setText("Data:");

        lblCidade.setText("Modo:");

        lblTelefone.setText("Situação:");

        botaosalvar.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        botaosalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/corretora_cunha/imgs/save.png"))); // NOI18N
        botaosalvar.setText("Salvar dados");
        botaosalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaosalvarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblNome)
                        .addGap(18, 18, 18)
                        .addComponent(data_neg, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(modo_neg, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblTelefone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(situacao_neg, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botaosalvar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(data_neg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCidade)
                    .addComponent(modo_neg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefone)
                    .addComponent(situacao_neg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaosalvar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Clientes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Monotype Corsiva", 0, 18), new java.awt.Color(8, 89, 43))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(8, 89, 43));

        tab_consultaCli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome"
            }
        ));
        tab_consultaCli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_consultaCliMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tab_consultaCli);

        btnAddCliente.setFont(new java.awt.Font("Monotype Corsiva", 0, 14)); // NOI18N
        btnAddCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/corretora_cunha/imgs/plusBlue2.png"))); // NOI18N
        btnAddCliente.setText("Adicionar Cliente");
        btnAddCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddClienteMouseClicked(evt);
            }
        });

        btnRetirarCli.setFont(new java.awt.Font("Monotype Corsiva", 0, 14)); // NOI18N
        btnRetirarCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/corretora_cunha/imgs/error2.png"))); // NOI18N
        btnRetirarCli.setText("Retirar Cliente selecionado");
        btnRetirarCli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRetirarCliMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnAddCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(btnRetirarCli)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddCliente)
                    .addComponent(btnRetirarCli))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Corretores", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Monotype Corsiva", 0, 18), new java.awt.Color(8, 89, 43))); // NOI18N

        tab_consultaCor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome"
            }
        ));
        tab_consultaCor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_consultaCorMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tab_consultaCor);

        btnAddCorretor.setFont(new java.awt.Font("Monotype Corsiva", 0, 14)); // NOI18N
        btnAddCorretor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/corretora_cunha/imgs/plusBlue2.png"))); // NOI18N
        btnAddCorretor.setText("Adicionar Corretor");
        btnAddCorretor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddCorretorMouseClicked(evt);
            }
        });

        btnRetirarCor.setFont(new java.awt.Font("Monotype Corsiva", 0, 14)); // NOI18N
        btnRetirarCor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/corretora_cunha/imgs/error2.png"))); // NOI18N
        btnRetirarCor.setText("Retirar Corretor selecionado");
        btnRetirarCor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRetirarCorMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnAddCorretor)
                        .addGap(18, 18, 18)
                        .addComponent(btnRetirarCor)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddCorretor)
                    .addComponent(btnRetirarCor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Propriedades", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Monotype Corsiva", 0, 18), new java.awt.Color(8, 89, 43))); // NOI18N

        tab_consultaProp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome"
            }
        ));
        tab_consultaProp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_consultaPropMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tab_consultaProp);

        btnAddPropRural.setFont(new java.awt.Font("Monotype Corsiva", 0, 14)); // NOI18N
        btnAddPropRural.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/corretora_cunha/imgs/plusBlue2.png"))); // NOI18N
        btnAddPropRural.setText("Adicionar Propriedade Rural");
        btnAddPropRural.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddPropRuralMouseClicked(evt);
            }
        });

        btnRetirarProp.setFont(new java.awt.Font("Monotype Corsiva", 0, 14)); // NOI18N
        btnRetirarProp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/corretora_cunha/imgs/error2.png"))); // NOI18N
        btnRetirarProp.setText("Retirar Propriedade selecionada");
        btnRetirarProp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRetirarPropMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddPropRural)
                            .addComponent(btnRetirarProp))
                        .addGap(0, 249, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(btnAddPropRural)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRetirarProp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(lblNomeSistema)
                            .addGap(155, 155, 155)
                            .addComponent(lblNegocio)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnExcluir, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btVoltar, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(id_neg, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNomeSistema)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lblNegocio))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btVoltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExcluir)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(id_neg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaosalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaosalvarMouseClicked
        if (verificaPreenchimento()) {
            if (gravar_alterar == 1) {
                gravar();
                gravar_alterar = 2;
            } else {
                if (gravar_alterar == 2) {
                    alterar();
                    //preencheTabela(buscar.getText().toUpperCase());
                    // gravar_alterar = 0;

                } else {
                    JOptionPane.showMessageDialog(null, "Erro no Sistema!!!");
                }
            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_botaosalvarMouseClicked

    private void btVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btVoltarMouseClicked
        new NegocioVIEW().setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btVoltarMouseClicked

    private void btnAddClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddClienteMouseClicked

        //Pega codigo negocio
        new ClienteVIEW(Integer.parseInt(id_neg.getText())).setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddClienteMouseClicked

    private void btnAddCorretorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddCorretorMouseClicked

        new CorretorVIEW(Integer.parseInt(id_neg.getText())).setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddCorretorMouseClicked

    private void btnAddPropRuralMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddPropRuralMouseClicked
        new PropriedadeRurais(Integer.parseInt(id_neg.getText())).setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddPropRuralMouseClicked

    private void btnExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcluirMouseClicked
        //Chamar método excluir
        excluir();
        limpaCampos();
        new NegocioVIEW().setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcluirMouseClicked

    private void btnRetirarCliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRetirarCliMouseClicked
        retirarCliente(clienteDTO);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRetirarCliMouseClicked

    private void tab_consultaCliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_consultaCliMouseClicked
        clienteDTO.setId_cli(Integer.parseInt(String.valueOf(tab_consultaCli.getValueAt(tab_consultaCli.getSelectedRow(), 0))));
        // TODO add your handling code here:
    }//GEN-LAST:event_tab_consultaCliMouseClicked

    private void btnRetirarCorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRetirarCorMouseClicked
    retirarCorretor(corretorDTO);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRetirarCorMouseClicked

    private void btnRetirarPropMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRetirarPropMouseClicked
        retirarPropriedade(propriedadeDTO);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRetirarPropMouseClicked

    private void tab_consultaCorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_consultaCorMouseClicked
        corretorDTO.setId_cor(Integer.parseInt(String.valueOf(tab_consultaCor.getValueAt(tab_consultaCor.getSelectedRow(), 0))));
        // TODO add your handling code here:
    }//GEN-LAST:event_tab_consultaCorMouseClicked

    private void tab_consultaPropMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_consultaPropMouseClicked
        propriedadeDTO.setId_prop(Integer.parseInt(String.valueOf(tab_consultaProp.getValueAt(tab_consultaProp.getSelectedRow(), 0))));
        // TODO add your handling code here:
    }//GEN-LAST:event_tab_consultaPropMouseClicked

    /**
     * @param args the command line arguments
     */
   
 private boolean verificaPreenchimento() {
       return true;
    }//Fecha método verificaPreenchimento()
    
    private void limpaCampos() {
        id_neg.setText("");
        data_neg.setText("");
        situacao_neg.setText("");
        modo_neg.setText("");
        modelo_jtl_consultar_cli.setNumRows(0);
        modelo_jtl_consultar_cor.setNumRows(0);
        modelo_jtl_consultar_prop.setNumRows(0);
    }//Fecha método limpacampos
    
    private void gravar() {
        negocioDTO.setData_neg(data_neg.getText());
        negocioDTO.setSituacao_neg(situacao_neg.getText());
        negocioDTO.setModo_neg(modo_neg.getText());
        //negocioDTO.setId_cli_neg(buscaCliente(nome_cli.getSelectedItem().toString()));
        
        JOptionPane.showMessageDialog(null,
                negocioCTR.inserirNegocio(negocioDTO)
        );
        this.id_neg.setText(consultarId_neg(negocioDTO));
        liberaBotoes(true, true, true);
    }//Fecha método gravar()
    
     private void alterar() {
        negocioDTO.setData_neg(data_neg.getText());
        negocioDTO.setSituacao_neg(modo_neg.getText());
        negocioDTO.setModo_neg(situacao_neg.getText());
        negocioDTO.setId_neg(Integer.parseInt(id_neg.getText()));
        JOptionPane.showMessageDialog(null,
                negocioCTR.alterarNegocio(negocioDTO)
        );
    }//Fecha método alterar()
    
    
    private void retirarCliente(ClienteDTO clienteDTO){
        if (JOptionPane.showConfirmDialog(null, "Deseja Realmente retirar esse cliente do negócio?", "Aviso",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            //Excluir cliente do negocio
            JOptionPane.showMessageDialog(null, negocioCliCTR.excluirCliente(clienteDTO));
            //Atualizar tabela
            preencheTabelaCli(Integer.parseInt(this.id_neg.getText()));
        }
    }
    
    private void retirarCorretor(CorretorDTO corretorDTO){
        if (JOptionPane.showConfirmDialog(null, "Deseja Realmente retirar esse corretor do negócio?", "Aviso",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            //Excluir cliente do negocio
            JOptionPane.showMessageDialog(null, negocioCorCTR.excluirCorretor(corretorDTO));
            //Atualizar tabela
            preencheTabelaCor(Integer.parseInt(this.id_neg.getText()));
        }
    }
     
    private void retirarPropriedade(PropriedadeDTO propriedadeDTO){
        if (JOptionPane.showConfirmDialog(null, "Deseja Realmente retirar essa Propriedade do negócio?", "Aviso",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            //Excluir cliente do negocio
            JOptionPane.showMessageDialog(null, negocioPropCTR.excluirPropriedade(propriedadeDTO));
            //Atualizar tabela
            preencheTabelaProp(Integer.parseInt(this.id_neg.getText()));
        }
    }
    
    private void excluir(){
        if (JOptionPane.showConfirmDialog(null, "Deseja Realmente excluir o negócio?", "Aviso", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            
            try {
                //Excluir clientes
                negocioCliCTR.excluirNegocioCliente(negocioCliDTO);
                //Excluir corretores
                negocioCorCTR.excluirNegocioCorretor(negocioCorDTO);
                //Excluir propriedades
                negocioPropCTR.excluirNegocioPropriedade(negocioPropDTO);
                //Excluir negocio base
                JOptionPane.showMessageDialog(null, negocioCTR.excluirNegocio(negocioDTO));
            } catch (Exception e) {
            }
        }
    }//Fecha método excluir()
    
    
    //Método para preencher dados do negocio pelo Id_neg
    private void preencherCampos(int id_neg){
        try {
            //buscar dados
            negocioDTO.setId_neg(id_neg);
            rs = negocioCTR.consultarNegocio(negocioDTO, 1);
            if (rs.next()) {
                this.id_neg.setText(rs.getString("id_neg"));
                this.data_neg.setText(rs.getString("data_neg"));
                this.situacao_neg.setText(rs.getString("situacao_neg"));
                this.modo_neg.setText(rs.getString("modo_neg"));
            }
            preencheTabelaCli(id_neg);
            preencheTabelaCor(id_neg);
            preencheTabelaProp(id_neg);
        } catch (Exception e) {
        }
    }
    
    private String consultarId_neg(NegocioDTO negocioDTO){
        String codString="";
        try {
            rs = negocioCTR.consultarNegocio(negocioDTO, 2);
            while (rs.next()) {
                int cod = rs.getInt("max_id");
                codString= String.valueOf(cod);
            }
            return codString;
         } catch (Exception erTab) {
            System.out.println("Erro SQL: " + erTab);
            return codString;
        }
    }
    
    //Método para realizar consulta e iniciar a preencher a tabela cliente
    private void preencheTabelaCli(int id_neg){
         try{
            //Array com o id dos clientes
            ArrayList<Integer> ids = new ArrayList<Integer>();
            //Limpa todas as linhas
            modelo_jtl_consultar_cli.setNumRows(0);
            //Set em id do negocio
            negocioCliDTO.setId_neg(id_neg);
            //Consultar os clientes do negocio
            rs = negocioCliCTR.consultarNegocioCli(negocioCliDTO, 1);
            //Preenchendo a tabela
            while (rs.next()) {
                //add o id do cliente no array
                ids.add(Integer.parseInt(rs.getString("id_cli")));
            }
            //preenche as linhas da tabela
            for(int i=0; ids.size()>=i; i++){
                modelo_jtl_consultar_cli.addRow(new Object[]{
                    ids.get(i), //id do cliente
                    consultarNomeCli(ids.get(i)) //nome do cliente
                });
            }
            
        }catch(Exception ex){
            System.out.println("Erro Consultar Cliente: " + ex);
        }
    }
    //Método para consultar o nome cliente pelo id
    private String consultarNomeCli(int id_cli){
        String nome = "";
        try {
            clienteDTO.setId_cli(id_cli);
            rs = clienteCTR.consultarCliente(clienteDTO, 1);
            //Enquanto tiver linhas - faça
            while (rs.next()) {
                nome= rs.getString("nome_cli");
            }
            return nome;
        } catch (Exception e) {
            return nome;
        }
    }
    
    
    //Método para realizar consulta e iniciar a preencher a tabela Corretor
    private void preencheTabelaCor(int id_neg){
         try{
            //Array com o id dos clientes
            ArrayList<Integer> ids = new ArrayList<Integer>();
            //Limpa todas as linhas
            modelo_jtl_consultar_cor.setNumRows(0);
            //Set em id do negocio
            negocioCorDTO.setId_neg(id_neg);
            //Consultar os clientes do negocio
            rs = negocioCorCTR.consultarNegocioCor(negocioCorDTO, 1);
            //Preenchendo a tabela
            while (rs.next()) {
                //add o id do cliente no array
                ids.add(Integer.parseInt(rs.getString("id_cor")));
            }
            //preenche as linhas da tabela
            for(int i=0; ids.size()>=i; i++){
                modelo_jtl_consultar_cor.addRow(new Object[]{
                    ids.get(i), //id do corretor
                    consultarNomeCor(ids.get(i)) //nome do corretor
                });
            }
            
        }catch(Exception ex){
            System.out.println("Erro preencheTabelaCor: " + ex);
        }
    }
    //Método para consultar o nome cliente pelo id
    private String consultarNomeCor(int id_cor){
        String nome = "";
        try {
            corretorDTO.setId_cor(id_cor);
            rs = corretorCTR.consultarCorretor(corretorDTO, 1);
            //Enquanto tiver linhas - faça
            while (rs.next()) {
                nome= rs.getString("nome_cor");
            }
            return nome;
        } catch (Exception e) {
            return nome;
        }
    }
    
    //Método para realizar consulta e iniciar a preencher a tabela Propriedade
    private void preencheTabelaProp(int id_neg){
         try{
            //Array com o id das propriedades
            ArrayList<Integer> ids = new ArrayList<Integer>();
            //Limpa todas as linhas
            modelo_jtl_consultar_prop.setNumRows(0);
            //Set em id da prop
            negocioPropDTO.setId_neg(id_neg);
            //Consultar as props do negocio
            rs = negocioPropCTR.consultarNegocioProp(negocioPropDTO, 1);
            //Preenchendo a tabela
            while (rs.next()) {
                //add o id do cliente no array
                ids.add(Integer.parseInt(rs.getString("id_prop")));
            }
            //preenche as linhas da tabela
            for(int i=0; ids.size()>=i; i++){
                modelo_jtl_consultar_prop.addRow(new Object[]{
                    ids.get(i), //id da prop
                    consultarNomeProp(ids.get(i)) //nome da prop
                });
            }
            
        }catch(Exception ex){
            System.out.println("Erro preencheTabelaCor: " + ex);
        }
    }
    //Método para consultar o nome cliente pelo id
    private String consultarNomeProp(int id_prop){
        String nome = "";
        try {
            propriedadeDTO.setId_prop(id_prop);
            rs = propriedadeCTR.consultarPropriedade(propriedadeDTO, 1);
            //Enquanto tiver linhas - faça
            while (rs.next()) {
                nome= rs.getString("nome_prop");
            }
            return nome;
        } catch (Exception e) {
            return nome;
        }
    }
  /*  private int buscaCliente(String nome_cli){
         try {
            clienteDTO.setNome_cli(nome_cli);
            rs = clienteCTR.consultarCliente(clienteDTO, 2);
            //Enquanto tiver linhas - faça
            while (rs.next()) {
                modelo_jtl_consultar_cli.addRow(new Object[]{
                    rs.getString("nome_cli"),
                    rs.getString("cidade_cli"),
                    rs.getString("tel_cli"),
                    rs.getString("email_cli"),});
            }
        } catch (Exception erTab) {
            System.out.println("Erro SQL: " + erTab);
        }
       return 0;
    }*/
    
    private void liberaBotoes(boolean a, boolean b, boolean c) {
        btnAddCliente.setEnabled(a);
        btnRetirarCli.setEnabled(a);
        tab_consultaCli.setEnabled(a);
        btnAddCorretor.setEnabled(b);
        btnRetirarCor.setEnabled(b);
        tab_consultaCor.setEnabled(b);
        btnAddPropRural.setEnabled(c);
        btnRetirarProp.setEnabled(c);
        tab_consultaProp.setEnabled(c);
    }//Fehca método liberaBotoes(boolean a, boolean b, boolean c, boolean d, boolean e)
     
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel botaosalvar;
    private javax.swing.JLabel btVoltar;
    private javax.swing.JLabel btnAddCliente;
    private javax.swing.JLabel btnAddCorretor;
    private javax.swing.JLabel btnAddPropRural;
    private javax.swing.JLabel btnExcluir;
    private javax.swing.JLabel btnRetirarCli;
    private javax.swing.JLabel btnRetirarCor;
    private javax.swing.JLabel btnRetirarProp;
    private javax.swing.JTextField data_neg;
    private javax.swing.JTextField id_neg;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblNegocio;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNomeSistema;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JTextField modo_neg;
    private javax.swing.JTextField situacao_neg;
    private javax.swing.JTable tab_consultaCli;
    private javax.swing.JTable tab_consultaCor;
    private javax.swing.JTable tab_consultaProp;
    // End of variables declaration//GEN-END:variables
}
