/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.corretora_cunha.view.clientes;

import javax.swing.JOptionPane;
import br.com.corretora_cunha.dto.ClienteDTO;
import br.com.corretora_cunha.ctr.ClienteCTR;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author ra6sa
 */
public class ClientesCadastrar extends javax.swing.JFrame {
   
    private int gravar_alterar; //Variavel usada para saber se esta alterando o incluindo
    private ResultSet rs; // Variavel usada para preenchimeto da tabela e dos campos
    ClienteCTR clienteCTR = new ClienteCTR(); //Cria um obejto clienteCTR
    ClienteDTO clienteDTO = new ClienteDTO(); //Cria um objeto pessoaDTO
    /**
     * Creates new form ClientesCadastrar
     */
    public ClientesCadastrar() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.gravar_alterar=1;
        this.id_cli.disable();
    }
    
    public ClientesCadastrar(int id_cli) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.gravar_alterar=2;
        this.id_cli.disable();
        preencherCampos(id_cli);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNomeSistema = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        nome_cli = new javax.swing.JTextField();
        lblCidade = new javax.swing.JLabel();
        cidade_cli = new javax.swing.JTextField();
        lblTelefone = new javax.swing.JLabel();
        tel_cli = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        email_cli = new javax.swing.JTextField();
        botaosalvar = new javax.swing.JLabel();
        btVoltar = new javax.swing.JLabel();
        btnExcluir = new javax.swing.JLabel();
        id_cli = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(8, 89, 43)));

        lblNomeSistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/corretora_cunha/imgs/nome80.jpg"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(8, 89, 43));
        jLabel1.setText("Cliente");

        lblNome.setText("Nome:");

        lblCidade.setText("Cidade:");

        lblTelefone.setText("Telefone:");

        lblEmail.setText("E-mail:");

        botaosalvar.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        botaosalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/corretora_cunha/imgs/save.png"))); // NOI18N
        botaosalvar.setText("Salvar");
        botaosalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaosalvarMouseClicked(evt);
            }
        });

        btVoltar.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        btVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/corretora_cunha/imgs/left-arrow.png"))); // NOI18N
        btVoltar.setText("Voltar");
        btVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btVoltarMouseClicked(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/corretora_cunha/imgs/delete.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExcluirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblNomeSistema)
                                .addGap(63, 63, 63)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botaosalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(7, 7, 7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(lblNome))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(lblCidade)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cidade_cli)
                            .addComponent(nome_cli)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblEmail)
                            .addComponent(lblTelefone))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tel_cli)
                            .addComponent(email_cli)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(id_cli, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNomeSistema)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel1)))
                        .addGap(20, 20, 20)
                        .addComponent(id_cli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNome)
                            .addComponent(nome_cli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCidade)
                            .addComponent(cidade_cli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTelefone)
                            .addComponent(tel_cli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btVoltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaosalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(email_cli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaosalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaosalvarMouseClicked
         if (verificaPreenchimento()) {
            if (gravar_alterar == 1) {
                gravar();
                gravar_alterar = 2;
            } else {
                if (gravar_alterar == 2) {
                    alterar();
                    //preencheTabela(buscar.getText().toUpperCase());
                   // gravar_alterar = 0;

                } else {
                    JOptionPane.showMessageDialog(null, "Erro no Sistema!!!");
                }
            }
            new ClienteVIEW().setVisible(true);
            this.dispose();
            //liberaCampos(false);
            //liberaBotoes(true, false, false, false);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_botaosalvarMouseClicked

    private void btVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btVoltarMouseClicked
         new ClienteVIEW().setVisible(true);
         this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btVoltarMouseClicked

    private void btnExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcluirMouseClicked
        excluir();
        new ClienteVIEW().setVisible(true);
        this.dispose();
            // TODO add your handling code here:
    }//GEN-LAST:event_btnExcluirMouseClicked

    /**
     * @param args the command line arguments
     */
  
     private void preencherCampos(int id_cli){
        try {
            //buscar dados
            clienteDTO.setId_cli(id_cli);
            rs = clienteCTR.consultarCliente(clienteDTO, 1);
            if (rs.next()) {
                this.id_cli.setText(rs.getString("id_cli"));
                this.nome_cli.setText(rs.getString("nome_cli"));
                this.tel_cli.setText(rs.getString("tel_cli"));
                this.email_cli.setText(rs.getString("email_cli"));
                this.cidade_cli.setText(rs.getString("cidade_cli"));

            }
        } catch (Exception e) {
        }
    }
    
    private boolean verificaPreenchimento() {
        boolean resul = true; 
        if (nome_cli.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "O campo Nome deve ser preenchido");
            nome_cli.requestFocus();
            resul = false;
            if (cidade_cli.getText().equalsIgnoreCase("")) {
                JOptionPane.showMessageDialog(null, "O campo Cidade deve ser preenchido");
                cidade_cli.requestFocus();
                resul = false;
            } else {
                if (tel_cli.getText().equalsIgnoreCase("")) {
                    JOptionPane.showMessageDialog(null, "O campo Telefone deve ser preenchido");
                    tel_cli.requestFocus();
                    resul = false;
                } 
            }//Fecha else tel_cli
        } else {
           resul = true; 
        }
        return resul;
    }//Fecha método verificaPreenchimento()
    
    private void limpaCampos() {
        id_cli.setText("");
        nome_cli.setText("");
        tel_cli.setText("");
        email_cli.setText("");
        cidade_cli.setText("");
    }//Fecha método limpacampos
    
    private void gravar() {
        clienteDTO.setNome_cli(nome_cli.getText());
        clienteDTO.setCidade_cli(cidade_cli.getText());
        clienteDTO.setTel_cli(tel_cli.getText());
        clienteDTO.setEmail_cli(email_cli.getText());
        JOptionPane.showMessageDialog(null,
                clienteCTR.inserirCliente(clienteDTO)
        );
    }//Fecha método gravar()
    
    
    
    private void alterar() {
        clienteDTO.setNome_cli(nome_cli.getText());
        clienteDTO.setTel_cli(tel_cli.getText());
        clienteDTO.setEmail_cli(email_cli.getText());
        clienteDTO.setCidade_cli(cidade_cli.getText());
        clienteDTO.setId_cli(Integer.parseInt(id_cli.getText()));
        JOptionPane.showMessageDialog(null,
                clienteCTR.alterarCliente(clienteDTO)
        );
    }//Fecha método alterar()
    
    private void excluir(){
        if (JOptionPane.showConfirmDialog(null, "Deseja Realmente excluir o cliente?", "Aviso", 
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            try {
                JOptionPane.showMessageDialog(null, clienteCTR.excluirCliente(clienteDTO));
            } catch (Exception e) {
            }
        }
    }//Fecha método excluir()
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel botaosalvar;
    private javax.swing.JLabel btVoltar;
    private javax.swing.JLabel btnExcluir;
    private javax.swing.JTextField cidade_cli;
    private javax.swing.JTextField email_cli;
    private javax.swing.JTextField id_cli;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNomeSistema;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JTextField nome_cli;
    private javax.swing.JTextField tel_cli;
    // End of variables declaration//GEN-END:variables
}
