/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.corretora_cunha.view.clientes;

import javax.swing.table.DefaultTableModel;
import br.com.corretora_cunha.ctr.ClienteCTR;
import br.com.corretora_cunha.ctr.NegocioCliCTR;
import br.com.corretora_cunha.ctr.RelatorioCTR;
import br.com.corretora_cunha.dto.ClienteDTO;
import br.com.corretora_cunha.dto.NegocioCliDTO;
import br.com.corretora_cunha.view.PrincipalVIEW;
import br.com.corretora_cunha.view.clientes.ClientesCadastrar;
import br.com.corretora_cunha.view.negocio.NegocioCadastrar;
import javax.swing.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import net.sf.jasperreports.engine.JRException;


/**
 *
 * @author ra6sa
 */
public class ClienteVIEW extends javax.swing.JFrame {
    Map parametros = new HashMap();
    private ResultSet rs; // Variavel usada para preenchimeto da tabela e dos campos
    private DefaultTableModel modelo_jtl_consultar_cli; //Variavel para guardar o modelo da tabela
    private int id_neg = 0;
    ClienteDTO clienteDTO = new ClienteDTO(); //Cria um objeto clienteDTO
    ClienteCTR clienteCTR = new ClienteCTR(); //Cria um obejto clienteCTR
    NegocioCliDTO negocioCliDTO = new NegocioCliDTO(); //Cria um objeto clienteDTO
    NegocioCliCTR negocioCliCTR = new NegocioCliCTR(); //Cria um obejto clienteCTR
  
    /**
     * Creates new form Clientes
     */
    public ClienteVIEW() {
       initComponents();
       this.setLocationRelativeTo(null);
       modelo_jtl_consultar_cli = (DefaultTableModel) tab_consulta.getModel();
       preencheTabela();
       btnAdd.setVisible(false);
       liberaBotoes(false);
    }
    
     public ClienteVIEW(int id_neg) {
       initComponents();
       this.setLocationRelativeTo(null);
       modelo_jtl_consultar_cli = (DefaultTableModel) tab_consulta.getModel();
       preencheTabela();
       btnAdd.setVisible(true);
       this.id_neg = id_neg;
       liberaBotoes(false);
    }

    
   
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JPanel();
        lblNomeSistema = new javax.swing.JLabel();
        lblClientes = new javax.swing.JLabel();
        lblCadastrar = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JLabel();
        btnRelatorio = new javax.swing.JLabel();
        buscar = new javax.swing.JTextField();
        botaobuscar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab_consulta = new javax.swing.JTable();
        btnAdd = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        desktopPane.setBackground(new java.awt.Color(255, 255, 255));
        desktopPane.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(8, 89, 43)));

        lblNomeSistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/corretora_cunha/imgs/nome80.jpg"))); // NOI18N

        lblClientes.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        lblClientes.setForeground(new java.awt.Color(8, 89, 43));
        lblClientes.setText("Clientes");

        lblCadastrar.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        lblCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/corretora_cunha/imgs/plus.png"))); // NOI18N
        lblCadastrar.setText("Cadastrar cliente");
        lblCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCadastrarMouseClicked(evt);
            }
        });

        btnVoltar.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/corretora_cunha/imgs/left-arrow.png"))); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVoltarMouseClicked(evt);
            }
        });

        btnRelatorio.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        btnRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/corretora_cunha/imgs/relatorio.png"))); // NOI18N
        btnRelatorio.setText("Emitir relatório");
        btnRelatorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRelatorioMouseClicked(evt);
            }
        });

        botaobuscar.setFont(new java.awt.Font("Monotype Corsiva", 0, 15)); // NOI18N
        botaobuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/corretora_cunha/imgs/search.png"))); // NOI18N
        botaobuscar.setText("Buscar por cidade");
        botaobuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaobuscarMouseClicked(evt);
            }
        });

        tab_consulta.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        tab_consulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Cidade", "Telefone", "E-mail"
            }
        ));
        tab_consulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_consultaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tab_consulta);

        btnAdd.setFont(new java.awt.Font("Monotype Corsiva", 0, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(51, 0, 153));
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/corretora_cunha/imgs/plusBlue.png"))); // NOI18N
        btnAdd.setText("Adicionar cliente selecionado ao negócio");
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopPaneLayout.createSequentialGroup()
                .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(desktopPaneLayout.createSequentialGroup()
                        .addComponent(lblNomeSistema)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnVoltar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCadastrar, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(desktopPaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(desktopPaneLayout.createSequentialGroup()
                                .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaobuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnRelatorio, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnAdd)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopPaneLayout.createSequentialGroup()
                .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(desktopPaneLayout.createSequentialGroup()
                        .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNomeSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(desktopPaneLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(lblClientes)))
                        .addGap(18, 18, 18)
                        .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaobuscar))
                        .addGap(27, 27, 27))
                    .addGroup(desktopPaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVoltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCadastrar)
                        .addGap(20, 20, 20)
                        .addComponent(btnRelatorio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadastrarMouseClicked
        new ClientesCadastrar().setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCadastrarMouseClicked

    private void botaobuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaobuscarMouseClicked

        
        pesquisaTabela(buscar.getText().toUpperCase());
        // TODO add your handling code here:
    }//GEN-LAST:event_botaobuscarMouseClicked

    private void tab_consultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_consultaMouseClicked
        
        clienteDTO.setId_cli(Integer.parseInt(String.valueOf(tab_consulta.getValueAt(tab_consulta.getSelectedRow(), 0))));
        liberaBotoes(true);
        if(id_neg==0){
            new ClientesCadastrar(clienteDTO.getId_cli()).setVisible(true);
            this.dispose();
        }
// TODO add your handling code here:
    }//GEN-LAST:event_tab_consultaMouseClicked

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
        gravar_cliente();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddMouseClicked

    private void btnVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarMouseClicked
        if(this.id_neg == 0){
            //pagina inicial
            new PrincipalVIEW().setVisible(true);
            this.dispose();
        }else{
            //abrir o cadastro de negocio
            new NegocioCadastrar(id_neg).setVisible(true);
            this.dispose();
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVoltarMouseClicked

    private void btnRelatorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRelatorioMouseClicked

        RelatorioCTR relatorioCTR = new RelatorioCTR();
        try {
            try {
                relatorioCTR.abrirRelatorio("feg.jasper", "Relatório de Clientes!", parametros).setVisible(true);
                // TODO add your handling code here:
            } catch (SQLException ex) {
                System.out.println("sql erro");
                JOptionPane.showMessageDialog(null,
                "Erro ao gerar relatório" + ex
            );
            }
        } catch (JRException ex) {
            System.out.println("jr erro");
            JOptionPane.showMessageDialog(null,
                "Erro ao gerar relatório" + ex
            );
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRelatorioMouseClicked

    /**
     * @param args the command line arguments
     */
   
    
    private void liberaBotoes(boolean a) {
        btnAdd.setEnabled(a);
    }//Fehca método liberaBotoes(boolean a, boolean b, boolean c, boolean d, boolean e)
    
    private void preencheTabela() {
        try {
            //Limpa todas as linhas
            modelo_jtl_consultar_cli.setNumRows(0);

            rs = clienteCTR.consultarCliente(clienteDTO, 5);
            //Enquanto tiver linhas - faça
            while (rs.next()) {
                modelo_jtl_consultar_cli.addRow(new Object[]{
                    rs.getString("id_cli"),
                    rs.getString("nome_cli"),
                    rs.getString("cidade_cli"),
                    rs.getString("tel_cli"),
                    rs.getString("email_cli"),});
            }
        } catch (Exception erTab) {
            System.out.println("Erro SQL: " + erTab);
        }
    }//Fecha método preencheTabela(String nom_pes)
     
    private void pesquisaTabela(String cidade_cli) {
        try {
            //Limpa todas as linhas
            modelo_jtl_consultar_cli.setNumRows(0);

            clienteDTO.setCidade_cli(cidade_cli);
            rs = clienteCTR.consultarCliente(clienteDTO, 3);
            //Enquanto tiver linhas - faça
            while (rs.next()) {
                modelo_jtl_consultar_cli.addRow(new Object[]{
                    rs.getString("id_cli"),
                    rs.getString("nome_cli"),
                    rs.getString("cidade_cli"),
                    rs.getString("tel_cli"),
                    rs.getString("email_cli"),});
            }
        } catch (Exception erTab) {
            System.out.println("Erro SQL: " + erTab);
        }
    }//Fecha método preencheTabela(String nom_pes)
     
    private void gravar_cliente() {
        negocioCliDTO.setId_neg(this.id_neg);
        negocioCliDTO.setId_cli(clienteDTO.getId_cli());
        System.out.println("Gravando Id_neg: "+ this.id_neg+" id_cli: "+ clienteDTO.getId_cli());
        JOptionPane.showMessageDialog(null,
                negocioCliCTR.inserirNegocioCli(negocioCliDTO)
        );
    }//Fecha método gravar()
    
    
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel botaobuscar;
    private javax.swing.JLabel btnAdd;
    private javax.swing.JLabel btnRelatorio;
    private javax.swing.JLabel btnVoltar;
    private javax.swing.JTextField buscar;
    private javax.swing.JPanel desktopPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCadastrar;
    private javax.swing.JLabel lblClientes;
    private javax.swing.JLabel lblNomeSistema;
    private javax.swing.JTable tab_consulta;
    // End of variables declaration//GEN-END:variables
}
