/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.corretora_cunha.view.propriedades;

import br.com.corretora_cunha.ctr.NegocioPropCTR;
import br.com.corretora_cunha.ctr.PropriedadeCTR;
import br.com.corretora_cunha.ctr.RelatorioCTR;
import br.com.corretora_cunha.dto.NegocioPropDTO;
import br.com.corretora_cunha.dto.PropriedadeDTO;
import br.com.corretora_cunha.view.PrincipalVIEW;
import br.com.corretora_cunha.view.negocio.NegocioCadastrar;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author ra6sa
 */
public class PropriedadeRurais extends javax.swing.JFrame {
     Map parametros = new HashMap();
    private ResultSet rs; // Variavel usada para preenchimeto da tabela e dos campos
    private DefaultTableModel modelo_jtl_consultar_cli; //Variavel para guardar o modelo da tabela
    private int id_neg = 0;
    PropriedadeDTO propriedadeDTO = new PropriedadeDTO(); //Cria um objeto propriedadeDTO
    PropriedadeCTR propriedadeCTR = new PropriedadeCTR(); //Cria um obejto propriedadeCTR
    NegocioPropDTO negocioPropDTO = new NegocioPropDTO(); //Cria um objeto NegocioPropriedadeDTO
    NegocioPropCTR negocioPropCTR = new NegocioPropCTR(); //Cria um obejto negocioPropriedadeCTR
    /**
     * Creates new form PropriedadeRurais
     */
    public PropriedadeRurais() {
       
        initComponents();
        this.setLocationRelativeTo(null);
        modelo_jtl_consultar_cli = (DefaultTableModel) tab_consulta.getModel();
        preencheTabela("RURAL");
        btnAdd.setVisible(false);
    }
    
    public PropriedadeRurais(int id_neg) {
       initComponents();
       modelo_jtl_consultar_cli = (DefaultTableModel) tab_consulta.getModel();
       preencheTabela("RURAL");
       btnAdd.setVisible(true);
       this.id_neg = id_neg;
       liberaBotoes(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNomeSistema = new javax.swing.JLabel();
        lblPropriedadesRurais = new javax.swing.JLabel();
        lblCadastroPropriedade = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab_consulta = new javax.swing.JTable();
        buscar = new javax.swing.JTextField();
        botaobuscar = new javax.swing.JLabel();
        btnAdd = new javax.swing.JLabel();
        btnVoltar1 = new javax.swing.JLabel();
        btnRelatorio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(8, 89, 43)));

        lblNomeSistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/corretora_cunha/imgs/nome80.jpg"))); // NOI18N

        lblPropriedadesRurais.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        lblPropriedadesRurais.setForeground(new java.awt.Color(8, 89, 43));
        lblPropriedadesRurais.setText("Propriedades Rurais");

        lblCadastroPropriedade.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        lblCadastroPropriedade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/corretora_cunha/imgs/plus.png"))); // NOI18N
        lblCadastroPropriedade.setText("Cadastrar propriedade rural");
        lblCadastroPropriedade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCadastroPropriedadeMouseClicked(evt);
            }
        });

        tab_consulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "UF", "Cidade", "Nome", "Area", "Valor"
            }
        ));
        tab_consulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_consultaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tab_consulta);

        botaobuscar.setFont(new java.awt.Font("Monotype Corsiva", 0, 14)); // NOI18N
        botaobuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/corretora_cunha/imgs/search.png"))); // NOI18N
        botaobuscar.setText("Buscar por cidade");
        botaobuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaobuscarMouseClicked(evt);
            }
        });

        btnAdd.setFont(new java.awt.Font("Monotype Corsiva", 0, 15)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(51, 0, 153));
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/corretora_cunha/imgs/plusBlue.png"))); // NOI18N
        btnAdd.setText("Adicionar propriedade selecionada ao negócio");
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });

        btnVoltar1.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        btnVoltar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/corretora_cunha/imgs/left-arrow.png"))); // NOI18N
        btnVoltar1.setText("Voltar");
        btnVoltar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVoltar1MouseClicked(evt);
            }
        });

        btnRelatorio.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        btnRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/corretora_cunha/imgs/relatorio.png"))); // NOI18N
        btnRelatorio.setText("Emitir relatório");
        btnRelatorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRelatorioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botaobuscar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRelatorio)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblNomeSistema)
                        .addGap(124, 124, 124)
                        .addComponent(lblPropriedadesRurais)
                        .addGap(102, 102, 102)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnVoltar1)
                            .addComponent(lblCadastroPropriedade)))
                    .addComponent(btnAdd))
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPropriedadesRurais)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnVoltar1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCadastroPropriedade)))
                        .addGap(3, 3, 3)
                        .addComponent(btnRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAdd)
                        .addGap(20, 20, 20))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblNomeSistema)
                        .addGap(72, 72, 72)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaobuscar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCadastroPropriedadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadastroPropriedadeMouseClicked
        new PropriedadeRuraisCadastro().setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCadastroPropriedadeMouseClicked

    private void botaobuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaobuscarMouseClicked

        pesquisaTabela(buscar.getText().toUpperCase());
        // TODO add your handling code here:
    }//GEN-LAST:event_botaobuscarMouseClicked

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
        gravar_propriedade();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddMouseClicked

    private void tab_consultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_consultaMouseClicked
        propriedadeDTO.setId_prop(Integer.parseInt(String.valueOf(tab_consulta.getValueAt(tab_consulta.getSelectedRow(), 0))));
        liberaBotoes(true);
         if(id_neg==0){
            new PropriedadeRuraisCadastro(propriedadeDTO.getId_prop()).setVisible(true);
            this.dispose();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_tab_consultaMouseClicked

    private void btnVoltar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltar1MouseClicked
        if(this.id_neg == 0){
            //pagina inicial
            new PrincipalVIEW().setVisible(true);
            this.dispose();
        }else{
            //abrir o cadastro de negocio
            new NegocioCadastrar(id_neg).setVisible(true);
            this.dispose();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVoltar1MouseClicked

    private void btnRelatorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRelatorioMouseClicked
         RelatorioCTR relatorioCTR = new RelatorioCTR();
        try {
            try {
                relatorioCTR.abrirRelatorio("PropriedadeR.jasper", "Relatório de Propriedades!", parametros).setVisible(true);

                // TODO add your handling code here:
            } catch (SQLException ex) {
               
                System.out.println("sql erro");
                JOptionPane.showMessageDialog(null,
                "Erro ao gerar relatório" + ex
            );
            }
        } catch (JRException ex) {
            System.out.println("jr erro");
            JOptionPane.showMessageDialog(null,
                "Erro ao gerar relatório" + ex
            );
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRelatorioMouseClicked

    /**
     * @param args the command line arguments
     */
   

    private void preencheTabela(String tipo_prop) {
        try {
            //Limpa todas as linhas
            modelo_jtl_consultar_cli.setNumRows(0);

            propriedadeDTO.setTipo_prop(tipo_prop);
            rs = propriedadeCTR.consultarPropriedade(propriedadeDTO, 7);
            //Enquanto tiver linhas - faça
            while (rs.next()) {
                modelo_jtl_consultar_cli.addRow(new Object[]{
                    rs.getString("id_prop"),
                    rs.getString("estado_prop"),
                    rs.getString("cidade_prop"),
                    rs.getString("nome_prop"),
                    rs.getString("area_prop"),
                    rs.getString("valor_prop"),});
            }
        } catch (Exception erTab) {
            System.out.println("Erro SQL: " + erTab);
        }
    }//Fecha método preencheTabela
     
    private void pesquisaTabela(String cidade_prop) {
        try {
            //Limpa todas as linhas
            modelo_jtl_consultar_cli.setNumRows(0);

            propriedadeDTO.setCidade_prop(cidade_prop);
            propriedadeDTO.setTipo_prop("RURAL");

            rs = propriedadeCTR.consultarPropriedade(propriedadeDTO, 3);
            //Enquanto tiver linhas - faça
            while (rs.next()) {
                modelo_jtl_consultar_cli.addRow(new Object[]{
                    rs.getString("id_prop"),
                    rs.getString("estado_prop"),
                    rs.getString("cidade_prop"),
                    rs.getString("nome_prop"),
                    rs.getString("area_prop"),
                    rs.getString("valor_prop"),});
            }
        } catch (Exception erTab) {
            System.out.println("Erro SQL: " + erTab);
        }
    }//Fecha método preencheTabela(String nom_pes)
    
    private void gravar_propriedade() {
        negocioPropDTO.setId_neg(this.id_neg);
        negocioPropDTO.setId_prop(propriedadeDTO.getId_prop());
        JOptionPane.showMessageDialog(null,
                negocioPropCTR.inserirNegocioProp(negocioPropDTO)
        );
    }//Fecha método gravar()
    
    private void liberaBotoes(boolean a) {
        btnAdd.setEnabled(a);
    }//Fehca método liberaBotoes(boolean a, boolean b, boolean c, boolean d, boolean e)
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel botaobuscar;
    private javax.swing.JLabel btnAdd;
    private javax.swing.JLabel btnRelatorio;
    private javax.swing.JLabel btnVoltar1;
    private javax.swing.JTextField buscar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCadastroPropriedade;
    private javax.swing.JLabel lblNomeSistema;
    private javax.swing.JLabel lblPropriedadesRurais;
    private javax.swing.JTable tab_consulta;
    // End of variables declaration//GEN-END:variables
}
