/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.corretora_cunha.view.corretores;

import br.com.corretora_cunha.ctr.CorretorCTR;
import br.com.corretora_cunha.ctr.NegocioCorCTR;
import br.com.corretora_cunha.dto.CorretorDTO;
import br.com.corretora_cunha.dto.NegocioCorDTO;
import br.com.corretora_cunha.view.PrincipalVIEW;
import br.com.corretora_cunha.view.negocio.NegocioCadastrar;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ra6sa
 */
public class CorretorVIEW extends javax.swing.JFrame {
     private ResultSet rs; // Variavel usada para preenchimeto da tabela e dos campos
     private DefaultTableModel modelo_jtl_consultar_cor; //Variavel para guardar o modelo da tabela
     private int id_neg = 0;
     CorretorDTO corretorDTO = new CorretorDTO(); //Cria um objeto corretorDTO
     CorretorCTR corretorCTR = new CorretorCTR(); //Cria um obejto corretorCTR
     NegocioCorDTO negocioCorDTO = new NegocioCorDTO(); //Cria um objeto negociocoreetorDTO
     NegocioCorCTR negocioCorCTR = new NegocioCorCTR(); //Cria um obejto negociocorretorCTR
    /**
     * Creates new form CorretorVIEW
     */
    public CorretorVIEW() {
        initComponents();
        this.setLocationRelativeTo(null);
        modelo_jtl_consultar_cor = (DefaultTableModel) tab_consulta.getModel();
        preencheTabela();
         btnAdd.setVisible(false);
    }
    
    public CorretorVIEW(int id_neg) {
       initComponents();
       this.setLocationRelativeTo(null);
       modelo_jtl_consultar_cor = (DefaultTableModel) tab_consulta.getModel();
       preencheTabela();
       btnAdd.setVisible(true);
       this.id_neg = id_neg;
       liberaBotoes(false, false, false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVoltar = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblNomeSistema = new javax.swing.JLabel();
        lblCorretores = new javax.swing.JLabel();
        btnVoltar1 = new javax.swing.JLabel();
        lblCadastrar = new javax.swing.JLabel();
        btnAdd = new javax.swing.JLabel();
        buscar = new javax.swing.JTextField();
        botaobuscar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab_consulta = new javax.swing.JTable();

        btnVoltar.setText("Voltar");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(8, 89, 43)));

        lblNomeSistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/corretora_cunha/imgs/nome80.jpg"))); // NOI18N

        lblCorretores.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        lblCorretores.setForeground(new java.awt.Color(8, 89, 43));
        lblCorretores.setText("Corretores");

        btnVoltar1.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        btnVoltar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/corretora_cunha/imgs/left-arrow.png"))); // NOI18N
        btnVoltar1.setText("Voltar");
        btnVoltar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVoltar1MouseClicked(evt);
            }
        });

        lblCadastrar.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        lblCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/corretora_cunha/imgs/plus.png"))); // NOI18N
        lblCadastrar.setText("Cadastrar corretor");
        lblCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCadastrarMouseClicked(evt);
            }
        });

        btnAdd.setFont(new java.awt.Font("Monotype Corsiva", 0, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(51, 0, 153));
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/corretora_cunha/imgs/plusBlue.png"))); // NOI18N
        btnAdd.setText("Adicionar corretor selecionado ao negócio");
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });

        botaobuscar.setFont(new java.awt.Font("Monotype Corsiva", 0, 15)); // NOI18N
        botaobuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/corretora_cunha/imgs/search.png"))); // NOI18N
        botaobuscar.setText("Buscar por cidade");
        botaobuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaobuscarMouseClicked(evt);
            }
        });

        tab_consulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Cidade", "Telefone", "E-mail"
            }
        ));
        tab_consulta.setGridColor(new java.awt.Color(102, 255, 51));
        tab_consulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_consultaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tab_consulta);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botaobuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAdd))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblNomeSistema)
                        .addGap(79, 79, 79)
                        .addComponent(lblCorretores)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCadastrar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnVoltar1, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVoltar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCadastrar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblCorretores))
                            .addComponent(lblNomeSistema))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaobuscar)
                            .addComponent(btnAdd))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaobuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaobuscarMouseClicked

        pesquisaTabela(buscar.getText().toUpperCase());
        // TODO add your handling code here:
    }//GEN-LAST:event_botaobuscarMouseClicked

    private void lblCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadastrarMouseClicked
        new CorretorCadastrar().setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCadastrarMouseClicked

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
        gravar_corretor();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddMouseClicked

    private void tab_consultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_consultaMouseClicked

        corretorDTO.setId_cor(Integer.parseInt(String.valueOf(tab_consulta.getValueAt(tab_consulta.getSelectedRow(), 0))));
        liberaBotoes(true, true, true);
        if(id_neg==0){
            new CorretorCadastrar(corretorDTO.getId_cor()).setVisible(true);
            this.dispose();
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_tab_consultaMouseClicked

    private void btnVoltar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltar1MouseClicked
        if(this.id_neg == 0){
            new PrincipalVIEW().setVisible(true);
            this.dispose();
        }else{
            //abrir o cadastro de negocio
            new NegocioCadastrar(id_neg).setVisible(true);
            this.dispose();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVoltar1MouseClicked

    /**
     * @param args the command line arguments
     */
   

    private void preencheTabela() {
        try {
            //Limpa todas as linhas
            modelo_jtl_consultar_cor.setNumRows(0);

            rs = corretorCTR.consultarCorretor(corretorDTO, 5);
            //Enquanto tiver linhas - faça
            while (rs.next()) {
                modelo_jtl_consultar_cor.addRow(new Object[]{
                    rs.getString("id_cor"),
                    rs.getString("nome_cor"),
                    rs.getString("cidade_cor"),
                    rs.getString("tel_cor"),
                    rs.getString("email_cor"),});
            }
        } catch (Exception erTab) {
            System.out.println("Erro SQL: " + erTab);
        }
    }//Fecha método preencheTabela(String nom_pes)
     
    private void pesquisaTabela(String cidade_cor) {
        try {
            //Limpa todas as linhas
            modelo_jtl_consultar_cor.setNumRows(0);

            corretorDTO.setCidade_cor(cidade_cor);
            rs = corretorCTR.consultarCorretor(corretorDTO, 3);
            //Enquanto tiver linhas - faça
            while (rs.next()) {
                modelo_jtl_consultar_cor.addRow(new Object[]{
                    rs.getString("id_cor"),
                    rs.getString("nome_cor"),
                    rs.getString("cidade_cor"),
                    rs.getString("tel_cor"),
                    rs.getString("email_cor"),});
            }
        } catch (Exception erTab) {
            System.out.println("Erro SQL: " + erTab);
        }
    }//Fecha método preencheTabela(String nom_pes)
    
    private void gravar_corretor() {
        negocioCorDTO.setId_neg(this.id_neg);
        negocioCorDTO.setId_cor(corretorDTO.getId_cor());
        JOptionPane.showMessageDialog(null,
                negocioCorCTR.inserirNegocioCor(negocioCorDTO)
        );
    }//Fecha método gravar()
    
    
    
     
    private void liberaBotoes(boolean a, boolean b, boolean c) {
        btnAdd.setEnabled(a);
    }//Fehca método liberaBotoes(boolean a, boolean b, boolean c, boolean d, boolean e)
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel botaobuscar;
    private javax.swing.JLabel btnAdd;
    private javax.swing.JLabel btnVoltar;
    private javax.swing.JLabel btnVoltar1;
    private javax.swing.JTextField buscar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCadastrar;
    private javax.swing.JLabel lblCorretores;
    private javax.swing.JLabel lblNomeSistema;
    private javax.swing.JTable tab_consulta;
    // End of variables declaration//GEN-END:variables
}
