/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.corretora_cunha.view.corretores;

import br.com.corretora_cunha.ctr.CorretorCTR;
import br.com.corretora_cunha.dto.CorretorDTO;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author ra6sa
 */
public class CorretorCadastrar extends javax.swing.JFrame {
    private int gravar_alterar; //Variavel usada para saber se esta alterando o incluindo
    private ResultSet rs; // Variavel usada para preenchimeto da tabela e dos campos
    CorretorCTR corretorCTR = new CorretorCTR(); //Cria um obejto corretorCTR
    CorretorDTO corretorDTO = new CorretorDTO(); //Cria um objeto pessoaDTO
    /**
     * Creates new form CorretorCadastrar
     */
    public CorretorCadastrar() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.gravar_alterar=1;
        this.id_cor.disable();
    }
    
    public CorretorCadastrar(int id_cor) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.gravar_alterar=2;
        this.id_cor.disable();
        preencherCampos(id_cor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNomeSistema = new javax.swing.JLabel();
        lblCadastro = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        nome_cor = new javax.swing.JTextField();
        lblCidade = new javax.swing.JLabel();
        cidade_cor = new javax.swing.JTextField();
        lblTelefone = new javax.swing.JLabel();
        tel_cor = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        email_cor = new javax.swing.JTextField();
        botaosalvar = new javax.swing.JLabel();
        lblCresci = new javax.swing.JLabel();
        cresci_cor = new javax.swing.JTextField();
        id_cor = new javax.swing.JTextField();
        btnExcluir = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(8, 89, 43)));

        lblNomeSistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/corretora_cunha/imgs/nome80.jpg"))); // NOI18N

        lblCadastro.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        lblCadastro.setForeground(new java.awt.Color(8, 89, 43));
        lblCadastro.setText("Corretor");

        lblNome.setText("Nome:");

        lblCidade.setText("Cidade:");

        lblTelefone.setText("Telefone:");

        lblEmail.setText("E-mail:");

        botaosalvar.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        botaosalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/corretora_cunha/imgs/save.png"))); // NOI18N
        botaosalvar.setText("Salvar");
        botaosalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaosalvarMouseClicked(evt);
            }
        });

        lblCresci.setText("Cresci:");

        btnExcluir.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/corretora_cunha/imgs/delete.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExcluirMouseClicked(evt);
            }
        });

        btnVoltar.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/corretora_cunha/imgs/left-arrow.png"))); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVoltarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblNomeSistema)
                .addGap(37, 37, 37)
                .addComponent(lblCadastro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVoltar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(botaosalvar)
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblEmail)
                                .addGap(18, 18, 18)
                                .addComponent(email_cor))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblCidade)
                                    .addComponent(lblNome))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nome_cor)
                                    .addComponent(cidade_cor)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(id_cor, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lblTelefone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tel_cor))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(25, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblCresci)
                                .addGap(18, 18, 18)
                                .addComponent(cresci_cor, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnExcluir, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblNomeSistema)
                        .addGap(11, 11, 11)
                        .addComponent(id_cor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNome)
                            .addComponent(nome_cor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCidade)
                            .addComponent(cidade_cor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTelefone)
                            .addComponent(tel_cor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmail)
                            .addComponent(email_cor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCresci)
                            .addComponent(cresci_cor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(btnVoltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaosalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lblCadastro)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaosalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaosalvarMouseClicked
        if (verificaPreenchimento()) {
            if (gravar_alterar == 1) {
                gravar();
                gravar_alterar = 2;
            } else {
                if (gravar_alterar == 2) {
                    alterar();
                    //preencheTabela(buscar.getText().toUpperCase());
                    // gravar_alterar = 0;

                } else {
                    JOptionPane.showMessageDialog(null, "Erro no Sistema!!!");
                }
            }
        }
        new CorretorVIEW().setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_botaosalvarMouseClicked

    private void btnExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcluirMouseClicked
        excluir();
        new CorretorVIEW().setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcluirMouseClicked

    private void btnVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarMouseClicked
         new CorretorVIEW().setVisible(true);
         this.dispose();
    }//GEN-LAST:event_btnVoltarMouseClicked

    /**
     * @param args the command line arguments
     */
   
    
     private void preencherCampos(int id_cor){
        try {
            //buscar dados
            corretorDTO.setId_cor(id_cor);
            rs = corretorCTR.consultarCorretor(corretorDTO, 1);
            if (rs.next()) {
                this.id_cor.setText(rs.getString("id_cor"));
                this.nome_cor.setText(rs.getString("nome_cor"));
                this.tel_cor.setText(rs.getString("tel_cor"));
                this.email_cor.setText(rs.getString("email_cor"));
                this.cidade_cor.setText(rs.getString("cidade_cor"));
                this.cresci_cor.setText(rs.getString("cresci_cor"));

            }
        } catch (Exception e) {
        }
    }
     
     private boolean verificaPreenchimento() {
        boolean resul = true; 
        if (nome_cor.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "O campo Nome deve ser preenchido");
            nome_cor.requestFocus();
            resul = false;
            if (cidade_cor.getText().equalsIgnoreCase("")) {
                JOptionPane.showMessageDialog(null, "O campo Cidade deve ser preenchido");
                cidade_cor.requestFocus();
                resul = false;
            } else {
                if (tel_cor.getText().equalsIgnoreCase("")) {
                    JOptionPane.showMessageDialog(null, "O campo Telefone deve ser preenchido");
                    tel_cor.requestFocus();
                    resul = false;
                } 
            }//Fecha else tel_cor
        } else {
           resul = true; 
        }
        return resul;
    }//Fecha método verificaPreenchimento()
    
    private void limpaCampos() {
        id_cor.setText("");
        nome_cor.setText("");
        tel_cor.setText("");
        email_cor.setText("");
        cidade_cor.setText("");
        cresci_cor.setText("");
    }//Fecha método limpacampos
    
    private void gravar() {
        corretorDTO.setNome_cor(nome_cor.getText());
        corretorDTO.setCidade_cor(cidade_cor.getText());
        corretorDTO.setTel_cor(tel_cor.getText());
        corretorDTO.setEmail_cor(email_cor.getText());
        corretorDTO.setCresci_cor(cresci_cor.getText());
        JOptionPane.showMessageDialog(null,
                corretorCTR.inserirCorretor(corretorDTO)
        );
    }//Fecha método gravar()
    
     private void alterar() {
        corretorDTO.setNome_cor(nome_cor.getText());
        corretorDTO.setTel_cor(tel_cor.getText());
        corretorDTO.setEmail_cor(email_cor.getText());
        corretorDTO.setCidade_cor(cidade_cor.getText());
        corretorDTO.setId_cor(Integer.parseInt(id_cor.getText()));
        corretorDTO.setCresci_cor(cresci_cor.getText());
        JOptionPane.showMessageDialog(null,
                corretorCTR.alterarCorretor(corretorDTO)
        );
    }//Fecha método alterar()

      private void excluir(){
        if (JOptionPane.showConfirmDialog(null, "Deseja Realmente excluir o corretor?", "Aviso", 
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            try {
                JOptionPane.showMessageDialog(null, corretorCTR.excluirCorretor(corretorDTO));
            } catch (Exception e) {
            }
        }
    }//Fecha método excluir()
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel botaosalvar;
    private javax.swing.JLabel btnExcluir;
    private javax.swing.JLabel btnVoltar;
    private javax.swing.JTextField cidade_cor;
    private javax.swing.JTextField cresci_cor;
    private javax.swing.JTextField email_cor;
    private javax.swing.JTextField id_cor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCadastro;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblCresci;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNomeSistema;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JTextField nome_cor;
    private javax.swing.JTextField tel_cor;
    // End of variables declaration//GEN-END:variables
}
